name: fluro
description: Fluro is a null-safe Flutter routing library that adds flexible routing options like wildcards, named parameters and clear route definitions.
version: 2.0.5
homepage: https://github.com/lukepighetti/fluro

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
